### ISSUE TITLE
"Repeat" Action Handler

### ISSUE THREAD

**Issue by vlad-tkachenko** [FireBlinkLTD/fbl#11]
Sometimes it may be useful to repeat some actions multiple times, but manually duplicating it's configuration inside the sequence/parallel action handler might be a pain.

Consider creating new "repeat" action that accepts following options:

```yaml
# number of times to repeat action
times: 5

# some action to repeat
# iteration index should also be available for EJS template of the action
# index should always start with 0
action:
  dummy: 'Index: <%- index %>'

# Whether to run all actions in parallel or in a sequence, default value: false
async: true
```
