### ISSUE TITLE
CLI Reporting

### ISSUE THREAD

**Issue by vlad-tkachenko** [FireBlinkLTD/fbl#126]
Add ability to register reporting records that should be printed to console at the end of execution.

Keeping an eye on intermediate logs might not be the best option for user, but looking into well formatted report in the end - is a nice option.

Also action handler "report" should be created. Suggested format:

```yaml
report:
  title: string
  # if status matches one of 3 default ones - output will be colored in GREEN, RED or YELLOW
  status: SUCCESS | FAIL | SKIPPED | else
  # will not be part of the printed table, but may be used programmatically for future needs 
  payload: any 
```
