### ISSUE TITLE
Add support of global plugin registry

### ISSUE THREAD

**Issue by vlad-tkachenko** [FireBlinkLTD/fbl#14]
Need to give option for user to store his/her default list of plugins inside the user's homedir config file at path  `$HOME/.fbl/config`

Config should be presented with a YAML formatted content:

```yaml
plugins:
 - fbl-test-plugin

secrets:
 shhhh: true

context:
 defaultValue: 'no'
```
