### ISSUE TITLE
Add ability to reference non-index file inside the package (tarball).

### ISSUE THREAD

**Issue by vlad-tkachenko** [FireBlinkLTD/fbl#166]
New CLI parameter: `-t --target <path>`

Attachment alternative syntax:
```yaml
'@': 
  # path to tarball
  path: flow.tar.gz
  # path inside the tarball
  target: path/to/flow.yml
```
