### ISSUE TITLE
Add ability to provide custom headers for remote flows requests

### ISSUE THREAD

**Issue by vlad-tkachenko** [FireBlinkLTD/fbl#167]
New CLI Parameter: `--http-header "<header: value>"`

Alternative attachment action handler syntax:
```
'@':
  path: https://somewhere.com/flow.tar.gz
  http:
    headers:
       Authentication: Basic something
```
