### ISSUE TITLE
New "While" Action Handler

### ISSUE THREAD

**Issue by vlad-tkachenko** [FireBlinkLTD/fbl#178]
```yaml
# repeat action while some action equals other value
while:
  # [required] value to compare
  value: '<%- ctx.something %>'
  # [required] compare with
  is: true
  # [required] action to run
  action:
```
