### ISSUE TITLE
Attachment flow wrong cache match

### ISSUE THREAD

**Issue by vlad-tkachenko** [FireBlinkLTD/fbl#185]
index.yml

```yaml
pipeline:
  '--':
    '@': a/
    '@': b/
```

a/index.yml
```yaml
pipeline:
  '--':
    '@': test.yml
```

b/index.yml
```yaml
pipeline:
  '--':
    '@': test.yml
```

a/test.yml
 ```yaml
pipeline:
  'ctx':
    '$.test': a
```

b/test.yml
 ```yaml
pipeline:
  'ctx':
    '$.test': b
```

In the end of execution ctx.test is "a", but should be "b"
