### ISSUE TITLE
Similar to "assignTo" property add another one "pushTo" that allows to push record(s) into array instead of overriding

### ISSUE THREAD

**Issue by vlad-tkachenko** [FireBlinkLTD/fbl#194]
```yaml
pushXXXTo:
   ctx: '$.test'
   secrets: '$.test'
   parameters: '$.test'
   # if value is array - push child objects instead of value itself
   children: true
```
