### ISSUE TITLE
Add option to cache remote flows inside ${FBL_HOME}/cache dir

### ISSUE THREAD

**Issue by vlad-tkachenko** [FireBlinkLTD/fbl#206]
Add new option for attachment action handler:

```yaml
'@':
  path: http://foo.bar
  # [optional] cache flow if specified remote URL and use it on subsequent executions
  cache: true
```

CLI:
```bash
fbl --cache http://foo.bar
```

Both should use $FBL_HOME env variable to find a place to store cache.
