### ISSUE TITLE
Local template processing and YAML unquoted scalar

### ISSUE THREAD

**Issue by vlad-tkachenko** [FireBlinkLTD/fbl#207]
Following flow:
```yaml
pipeline:
  ctx:
    '$.tst':
      inline: <%- '@test' %>
```

fails with: `YAMLException: bad indentation of a mapping entry`
