### ISSUE TITLE
Context assignment action handlers are not allowing to set boolean "false" value inline

### ISSUE THREAD

**Issue by vlad-tkachenko** [FireBlinkLTD/fbl#226]
Following action isn't working:

```yaml
ctx:
  '$.test':
    inline: false
```
