### ISSUE TITLE
References inside arrays are not get resolved.

### ISSUE THREAD

**Issue by vlad-tkachenko** [FireBlinkLTD/fbl#241]
In the following example reference is not resolved.

```yaml
pipeline:
  ctx:
    '$.test': 
      inline:
        - test: $ref:ctx.something    
```
