### ISSUE TITLE
New Action Hander: FS - Find files

### ISSUE THREAD

**Issue by vlad-tkachenko** [FireBlinkLTD/fbl#288]
Add new action handler that allows to find files by mask.

```yaml
find:
  # [required] path patterns to include in search
  include: 
    - /tmp/*
  # [optional] ignore files that match provided patterns
  ignore: 
    - /tmp/**/.*
  # [required] describe paths to store located files
  result:
    assignTo: 
    pushTo:
```
