### ISSUE TITLE
Update global config format.

### ISSUE THREAD

**Issue by vlad-tkachenko** [FireBlinkLTD/fbl#295]
Current global config tries to mimic CLI arguments, instead it should implement better structure.

```yaml
# [optional] list of plugins to automatically load upon launch
plugins: 
  - '@fbl-plugin/http'

# [optional] Default context values 
context: {
  # [optional]
  ctx: {}  
  
  # [optional]
  secrets: {}

  # [optional]
  parameters: {}

# [optional] execution report configuration
report:
  # [optional] reporter options
  options: {}

# [optional] additional request configuration for case when flow path is provided as URL
http:
  # [optional] additional HTTP headers to send with GET request
  headers: {}

# [optional] other options
other:
  # [optional] disable colorful output
  noColors: true
       
  # [optional] override default global EJS template delimiter
  # Default value: $
  globalTemplateDelimiter: '$'

  # [optional] override default local EJS template delimiter
  # Default value: %
  localTemplateDelimiter: '%'
```
