### ISSUE TITLE
context/secrets assignment handler - add pattern support

### ISSUE THREAD

**Issue by vlad-tkachenko** [FireBlinkLTD/fbl#44]
Treat all files as patters.

E.g:

```yaml
ctx:
  .:
    files:
      - *.yml
```
