### ISSUE TITLE
Action meta information.

### ISSUE THREAD

**Issue by vlad-tkachenko** [FireBlinkLTD/fbl#54]
Allow to specify any kind of meta information with action step. Reserve `$` as a prefix.

E.g.:

```yaml
version: 1.0.0
pipeline:
  $description: |-
    Detailed information about "ctx" action
  ctx: 
    '.':
      inline:
        option: value
```
